apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tetris-development
resources:
  - ../../base/
patches:
  # リソース要求
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tetris-deployment
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: "1G"
  # istio ingress gateway
  - target:
      group: networking.istio.io
      version: v1alpha3
      kind: Gateway
    patch: |
      - op: add
        path: /spec/selector/env
        value: development
