apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-deployment
  labels:
    app: tetris
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: tetris-container
          image: uzyexe/tetris:latest
          ports:
            - name: http-port
              containerPort: 80
          livenessProbe:
             httpGet:
               port: http-port
               path: /index.html
             initialDelaySeconds: 3
             periodSeconds: 10
          imagePullPolicy: Always
